### ISSUE TITLE
Rebuild lookups-dev on Dev CouchDB

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1077]
No rush on this, but there are ~ 20k lookups-dev records (vs 7k on prod) so we'll want to rebuild this. 
Anticipated steps:
- [ ] Set continuous replication job for master-dev -> lookups-dev to `continuous: false`
- [ ] Replicate lookups-dev to lookups-dev-20191122 to back it up
  - [ ] Back up views - manually or using updated tool when that's done #1059
- [ ] Noting Permissions, delete lookups-dev, then recreate it and add the same permissions
  - [ ] Restore views - manually/ #1059 when ready.
- [ ] Set continuous replication job back to `continuous:true` and double check the doc types are all current.
- [ ] Update SOP with this methodology (fairly standard couch practice, but the manual steps are a little annoying. #1059 should help make this a little easier)

This should rebuild lookups-dev in the nice minimal state.

**Comment by wsmith-nwfsc** [comment]
Also topic for discussion (can touch on it Monday meeting) is taxonomy-alias types in lookups is currently way too much data to conveniently sync to PouchDB clients, so we'll think about how to strip this down

**Comment by NickShafferNOAA** [comment]
Somehow this ticket flew under my radar until you commented there.

To add to this, deleting lookups-dev alone is not sufficient. The docs will need to be "manually" deleted (update each document with _deleted = true via simple script) to replicate the "deletion" to the user databases. Otherwise the lookup docs that have synced down to user databases will remain and we'll have duplicates. 

Unfortunately it isn't perfect as there isn't an easy, already built in way for purging those "deleted" documents from pouch memory: https://github.com/pouchdb/pouchdb/issues/802 

Side note: I had the SOP notes for refreshing master-dev and lookups-dev written down on paper and forgot to actually put them on our CouchDB SOP (oops). I have done that now.

**Comment by NickShafferNOAA** [comment]
Somehow this ticket flew under my radar until you commented there.

To add to this, deleting lookups-dev alone is not sufficient. The docs will need to be "manually" deleted (update each document with _deleted = true via simple script) to replicate the "deletion" to the user databases. Otherwise the lookup docs that have synced down to user databases will remain and we'll have duplicates.

Unfortunately it isn't perfect as there isn't an easy, already built in way for purging those "deleted" documents from pouch memory. An open request / issue: pouchdb issue 802

Side note: I had the SOP notes for refreshing master-dev and lookups-dev written down on paper and forgot to actually put them on our CouchDB SOP (oops). I have done that now.

**Comment by wsmith-nwfsc** [comment]
Ah right, the ol' delete on pouchdb issue. Looking forward to discussing our options here.

**Comment by NickShafferNOAA** [comment]
This was done in tandem to refreshing master dev. The steps to refresh lookups-dev are within the SOP document for refreshing master-dev.
