### ISSUE TITLE
Research Catch Tickets

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1110]
- [x] [populate groupings table in dev DB](https://github.com/nwfsc-fram/research-catch-db/issues/18)
- [x] [permit add/edit screen](https://github.com/nwfsc-fram/research-catch-db/issues/22)
- [x] [run main permit screen by Kate and Kayleigh, make final tweaks](https://github.com/nwfsc-fram/research-catch-db/issues)
- [x] [pull out dbconfig](https://github.com/nwfsc-fram/research-catch-db/issues/24)
- [x] [Update DB model](https://github.com/nwfsc-fram/research-catch-db/issues/25)

Bonus if the auth boatnet stuff is ready to go:
- [ ] [hook up login](https://github.com/nwfsc-fram/research-catch-db/issues/3)

**Comment by SaOgaz-NOAA** [comment]
Working on auth hook up with help frmo @wsmith-nwfsc. Good shot at having that done by the end of the week.

**Comment by SaOgaz-NOAA** [comment]
No luck, but it was a bonus goal anyway.
