### ISSUE TITLE
Research Catch Tickets

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1159]
- [x] [permit add/edit screen](https://github.com/nwfsc-fram/research-catch-db/issues/22)
- [x] [permit screen for staff](https://github.com/nwfsc-fram/research-catch-db/issues/11)
- [x] [staff/user smart routing](https://github.com/nwfsc-fram/research-catch-db/issues/28)

Possibly finish this?
- [ ] [login screen / auth hookup](https://github.com/nwfsc-fram/research-catch-db/issues/3)
