### ISSUE TITLE
Research Catch Stub

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1183]
- [x] [permit add/edit clean up](https://github.com/nwfsc-fram/research-catch-db/issues/31)
- [x] put in Kayleigh's grouping uptdates into the database
- [x] [required permit fields](https://github.com/nwfsc-fram/research-catch-db/issues/32)

If ready:
- [ ] [auth hookup](https://github.com/nwfsc-fram/research-catch-db/issues/3)

Bonus:
- [x] [format requirement for permit numbers](https://github.com/nwfsc-fram/research-catch-db/issues/34)
- [x] [new permit all fields required](https://github.com/nwfsc-fram/research-catch-db/issues/35)

Make note of bug... permit number field error check kicking off before I'd like it to, on intitial load

**Comment by SaOgaz-NOAA** [comment]
Not much of this tickets is done, so I'm gonna kick this into the next sprint.
