### ISSUE TITLE
Boatnet auth server + module updates for CouchDB

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nwfsc-fram/boatnet#1229]
Changing how pw is stored in CouchDB users. Details in internal gitlab.

Related fixes to be done at the same time:
- [x] #1258 - blocker issue for yarn link dev
- [ ] #1194 - ashop login fail
- [ ] #966 - applicationName to bn-auth
- [x] #1210 - username case sensitivity
- [ ] #1189 - roles for email logins
- [ ] #1147 - switching apps login issues

Possibly #1166 - log4js logging

**Comment by wsmith-nwfsc** [comment]
Resolved blocker issue with developing using ```yarn link```

**Comment by wsmith-nwfsc** [comment]
In progress, moving this top-level ticket to next sprint (sub tickets closed)
