### ISSUE TITLE
Research catch to-do list before user testing

### ISSUE THREAD

**Issue by SaOgaz-NOAA** [nwfsc-fram/boatnet#1541]
These tickets are all smaller items with issues in the actual github repo

- [x] [login page to-dos](https://github.com/nwfsc-fram/research-catch-db/issues/49)
- [x] [catch data lockdown](https://github.com/nwfsc-fram/research-catch-db/issues/48)
- [x] [check for repeat species groups](https://github.com/nwfsc-fram/research-catch-db/issues/47)
- [x] [typescript cleanup](https://github.com/nwfsc-fram/research-catch-db/issues/44)
- [x] [try again to get scroll with button working](https://github.com/nwfsc-fram/research-catch-db/issues/33) - spent some time on this and failed.... will come back to it
- [x] [check up on possible vuex bug](https://github.com/nwfsc-fram/research-catch-db/issues/27)
- [x] clean up catch submission failures like I did for grouping management page.
- [x] if user doesn't have role for this app, keep them on login page.
