### ISSUE TITLE
test misc ots fixes

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1842]
- [ ] departure date, return date, and observed required to submit missed trip (#1828)

- [ ] permit number auto-populated on missed trip, and in logbook (#1825)

- [ ] departure time on closed trip cards (#1824)

- [ ] staff can edit a closed trip (#1823)

- [ ] trip number shown in trip details (#1821)

- [ ] prevent dupe trip number (#1844)

**Comment by neilriley-NOAA** [comment]
@sethgerou-noaa  I am not able to enter a departure date and time for a missing trip under the staff mode.

**Comment by neilriley-NOAA** [comment]
All of these items are function properly.
