### ISSUE TITLE
test:

### ISSUE THREAD

**Issue by sethgerou-noaa** [nwfsc-fram/boatnet#1875]
- [ ] #1868 Only display gear type name 
- [ ] #1867 format haul dates in haul table
- [ ] #1864 increase fish ticket date field size
- [ ] #1870 logbook coordinate minutes should be less than go

**Comment by neilriley-NOAA** [comment]
All of these issues are functioning properly.
